import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#9DC08B",
    alignItems: "center",
    justifyContent: "center",
  },
  containerLogo: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 40,
  },
  imgLogo: {
    marginBottom: 20,
  },
  textBox: {
    width: "78%",
    alignItems: "flex-start",
  },
  textName: {
    fontSize: 20,
    color: "#2d2727",
    marginTop: 15,
    fontWeight: "bold",
    marginLeft: 3,
  },
  textInput: {
    backgroundColor: "#fff",
    width: "100%",
    padding: 8,
    paddingLeft: 10,
    borderRadius: 10,
  },
  textEmail: {
    fontSize: 20,
    color: "#2d2727",
    marginTop: 15,
    fontWeight: "bold",
    marginLeft: 3,
  },
  textCpf: {
    fontSize: 20,
    color: "#2d2727",
    marginTop: 15,
    fontWeight: "bold",
    marginLeft: 3,
  },
  textNumero: {
    fontSize: 20,
    color: "#2d2727",
    marginTop: 15,
    fontWeight: "bold",
    marginLeft: 3,
  },
  buttonCriar: {
    width: "55%",
    backgroundColor: "#609966",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    borderRadius: 10,
    marginTop: 25,
  },
  textButton: {
    fontSize: 18,
    color: "#fff",
    fontWeight: "bold",
  },
  buttonRetornar: {
    width: "55%",
    backgroundColor: "#609966",
    alignItems: "center",
    justifyContent: "center",
    padding: 10,
    borderRadius: 10,
    marginTop: 25,
    marginBottom: 30,
  },
  textBairro: {
    fontSize: 20,
    color: "#2d2727",
    marginTop: 15,
    fontWeight: "bold",
    marginLeft: 3,
  },
  textRua: {
    fontSize: 20,
    color: "#2d2727",
    marginTop: 15,
    fontWeight: "bold",
    marginLeft: 3,
  },
  textNumeroC: {
    fontSize: 20,
    color: "#2d2727",
    marginTop: 15,
    fontWeight: "bold",
    marginLeft: 3,
  },
  containerInfo:{
    width: "100%",
    alignItems: "flex-start",
    marginBottom: 30,
    fontWeight: "bold",
    marginLeft: 5,
  },
  textInfo:{
    fontSize: 20,
    color: "#2d2727",
    marginTop: 15,
    fontWeight: "bold",
    marginLeft: 5,
  }
});
